### Get update information
GET {{url}}v1/panopticon/core/update
X-Panopticon-Token: {{token}}

### Get update information, forced
GET {{url}}v1/panopticon/core/update?force=1
X-Panopticon-Token: {{token}}

### Get update information, with file checks
GET {{url}}v1/panopticon/core/update?check_files=1
X-Panopticon-Token: {{token}}

### Apply the default WordPress update
POST {{url}}v1/panopticon/core/update
X-Panopticon-Token: {{token}}

### Install a specific version (assuming WordPress knows about it)
POST {{url}}v1/panopticon/core/update?version=6.3.2
X-Panopticon-Token: {{token}}
