### TODO Refresh updates
POST {{url}}v1/panopticon/updates
X-Panopticon-Token: {{token}}

### TODO No extension to update
POST {{url}}v1/panopticon/update
X-Panopticon-Token: {{token}}

### TODO Update plugin
POST {{url}}v1/panopticon/update/plugin/foobar/foobar.php
X-Panopticon-Token: {{token}}

### TODO Update theme
POST {{url}}v1/panopticon/update/theme/sometheme
X-Panopticon-Token: {{token}}