### Refresh updates
POST {{url}}v1/panopticon/updates
X-Panopticon-Token: {{token}}

### No extension to update (error 404)
POST {{url}}v1/panopticon/update
X-Panopticon-Token: {{token}}

### TODO Update plugin
POST {{url}}v1/panopticon/update/plugin/safe-svg/safe-svg.php
X-Panopticon-Token: {{token}}

### TODO Update theme
POST {{url}}v1/panopticon/update/theme/sometheme
X-Panopticon-Token: {{token}}